name: java web-application deployment 1

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: deploy tomcat
      run: curl -v -u tomcat:tomcat -T /home/runner/work/java-apache-meven/java-apache-meven/target/SpringBootMavenExample-3.0-SNAPSHOT.war 'http://ec2-3-111-198-243.ap-south-1.compute.amazonaws.com:8080/manager/text/deploy?path=/myweb_dev_action&update=true'
